env:
  - OMERO_SERVER_VERSION=5.6

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  - git clone --recurse-submodules git://github.com/openmicroscopy/omero-test-infra .omero

script:
  - .omero/lib-docker
